//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuArte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public endereco()
        {
            this.organizacaos = new HashSet<organizacao>();
        }
    
        public string logradouro { get; set; }
        public Nullable<int> cep { get; set; }
        public Nullable<int> numero { get; set; }
        public int id_endereco { get; set; }
        public string complemento { get; set; }
        public Nullable<int> fk_bairro_id_bairro { get; set; }
    
        public virtual bairro bairro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacao> organizacaos { get; set; }
    }
}
