//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuArte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interage
    {
        public Nullable<int> fk_publicacao_id_publicacao { get; set; }
        public Nullable<int> fk_usuario_id_usuario { get; set; }
        public string comentario { get; set; }
        public int id_interacao { get; set; }
    
        public virtual publicacao publicacao { get; set; }
    }
}
