//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuArte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa_fisica
    {
        public int id_pessoa_fisica { get; set; }
        public int fk_usuario_id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
