//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuArte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class virtuarteEntities : DbContext
    {
        public virtuarteEntities()
            : base("name=virtuarteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bairro> bairroes { get; set; }
        public virtual DbSet<cidade> cidades { get; set; }
        public virtual DbSet<endereco> enderecoes { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<interage> interages { get; set; }
        public virtual DbSet<organizacao> organizacaos { get; set; }
        public virtual DbSet<pessoa_fisica> pessoa_fisica { get; set; }
        public virtual DbSet<publicacao> publicacaos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
